env = XCURSOR_SIZE,24 # 24px cursor size
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that

# Nvidia card nonsense
env = LIBVA_DRIVER_NAME, nvidia
env = XDG_SESSION_TYPE, wayland
env = GBM_BACKEND, nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME, nvidia

env = WLR_NO_HARDWARE_CURSORS, 1 # DO NOT REMOVE your cursor WILL become invisible bc why not <3